### ISSUE TITLE
generate lenses automatically 

### ISSUE THREAD

**Issue by sboosali** [dan-t/cabal-lenses#4]
compare: 

    makeLensesFor
              [ ("packageDescription", "packageDescriptionL")
              , ("genPackageFlags"   , "genPackageFlagsL")
              , ("condLibrary"       , "condLibraryL")
              , ("condExecutables"   , "condExecutablesL")
              , ("condTestSuites"    , "condTestSuitesL")
              , ("condBenchmarks"    , "condBenchmarksL")
              ] ''GenericPackageDescription

to:

    makeLensesWith (suffixedFields "L") ''GenericPackageDescription

which is easier to write, can't have typos, and (more importantly) is more future proof. 

I've already implemented it. I'd be happy to merge it. as well as bump cabal to 1.22.4.

**Comment by dan-t** [comment]
Hi Sam,

> I've already implemented it. I'd be happy to merge it. as well as bump cabal to 1.22.4.

Ok. :)

Greetings,
Daniel

**Comment by sboosali** [comment]
great!

**Comment by sboosali** [comment]
http://packdeps.haskellers.com/reverse/cabal-lenses

since you've authored both reverse dependencies (i.e. breakages can be handled), would you like me to make it build without warnings under `-Wall` on ghc 7.10.1? e.g. 

    lib/CabalLenses/Version.hs:12:1:
    Warning:The import of Control.Applicativeis redundant except perhaps to import instances fromControl.Applicative 

it would of course break the build on earlier compiler versions.

either way, I think it needs a major version bump for the updated Cabal version.

**Comment by dan-t** [comment]
Hi Sam,

On Thu, Oct 15, 2015 at 07:53:06AM -0700, Sam Boosalis wrote:
> since you've authored both reverse dependencies (i.e. breakages can be
> handled), would you like me to make it build without warnings under -Wall on
> ghc 7.10.1? e.g.

Just -W is enough.

> lib/CabalLenses/Version.hs:12:1:
> Warning:The import of Control.Applicativeis redundant except perhaps to import instances fromControl.Applicative
> 
> it would of course break the build on earlier compiler versions.

You can use:

   #if __GLASGOW_HASKELL__ < 710
   import Control.Applicative ((<$>))
   #endif

> either way, I think it needs a major version bump for the updated Cabal
> version.

Why that?


Greetings,
Daniel

**Comment by sboosali** [comment]
1. cool, haven't used CPP before. that seems better.

to avoid shadowing warnings, I hoisted some helper functions to the top
level, but didn't export them. let me know if that's okay, but I've been
bitten by name shadowing before (after a re-factoring), so I think it's a
good idea.

also, added an explicit PatternGuards extension to silence another warning.
(I'll put all this in the commit message)

2. oops, I misread cabal's latest version (1.22.4) as 1.24




On Thu, Oct 15, 2015 at 11:28 AM, Daniel Trstenjak <notifications@github.com
> wrote:

>
> Hi Sam,
>
> On Thu, Oct 15, 2015 at 07:53:06AM -0700, Sam Boosalis wrote:
> > since you've authored both reverse dependencies (i.e. breakages can be
> > handled), would you like me to make it build without warnings under
> -Wall on
> > ghc 7.10.1? e.g.
>
> Just -W is enough.
>
> > lib/CabalLenses/Version.hs:12:1:
> > Warning:The import of Control.Applicativeis redundant except perhaps to
> import instances fromControl.Applicative
> >
> > it would of course break the build on earlier compiler versions.
>
> You can use:
>
> #if __GLASGOW_HASKELL__ < 710
> import Control.Applicative ((<$>))
> #endif
>
> > either way, I think it needs a major version bump for the updated Cabal
> > version.
>
> Why that?
>
>
>
> Greetings,
> Daniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dan-t/cabal-lenses/issues/4#issuecomment-148481053>.
>



-- 



*(this message was composed with dictation: charitably interpret typos)Sam
Boosalis*
