### ISSUE TITLE
Inaccurate version bounds

### ISSUE THREAD

**Issue by hvr** [dan-t/cabal-lenses#8]
As can be seen on https://matrix.hackage.haskell.org/#/package/cabal-lenses the version (lower) bounds for `base` and `transformers` were inaccurate; (see also build failures below)

In my function as Hackage Trustee I've already corrected the metadata for the affected releases accordingly (i.e. do *not* need to upload a new release):

- https://hackage.haskell.org/package/cabal-lenses-0.7.1/revisions
- https://hackage.haskell.org/package/cabal-lenses-0.8.0/revisions
- https://hackage.haskell.org/package/cabal-lenses-0.9.0/revisions

Moreover, I've noticed that the *major* version increment over-signalling cabal-lenses-0.9.0 release merely changed the `.cabal` file at http://hdiff.luite.com/cgit/cabal-lenses/diff?id=0.9.0&id2=0.8.0 even though there don't appear to be breaking changes in the spirit of the [PVP](https://pvp.haskell.org/faq/). But also we have a more appropriate facility implemented in Hackage for this very use-case [Hackage Metadata Revisions](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md) which helps reduce the overhead for the Hackage ecosystem.

Please let me know if you have any questions.

----

```
Configuring library for cabal-lenses-0.9.0..
Preprocessing library for cabal-lenses-0.9.0..
Building library for cabal-lenses-0.9.0..

lib/CabalLenses/Utils.hs:10:8:
    Could not find module ‘Control.Monad.Trans.Except’
    It is a member of the hidden package ‘transformers-compat-0.5.1.3’.
    Perhaps you need to add ‘transformers-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-compat-0.6.2’.
    Perhaps you need to add ‘transformers-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.5.0’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.4.3.0’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
<<ghc: 356453816 bytes, 184 GCs, 11059166/32163584 avg/max bytes residency (8 samples), 85M in use, 0.00 INIT (0.00 elapsed), 0.10 MUT (0.10 elapsed), 0.26 GC (0.26 elapsed) :ghc>>
```

or

```
[ 7 of 11] Compiling CabalLenses.CondVars ( lib/CabalLenses/CondVars.hs, /tmp/matrix-worker/1546534388/dist-newstyle/build/x86_64-linux/ghc-7.4.2/cabal-lenses-0.9.0/build/CabalLenses/CondVars.o )
[ 8 of 11] Compiling CabalLenses.Traversals.Internal ( lib/CabalLenses/Traversals/Internal.hs, /tmp/matrix-worker/1546534388/dist-newstyle/build/x86_64-linux/ghc-7.4.2/cabal-lenses-0.9.0/build/CabalLenses/Traversals/Internal.o )

lib/CabalLenses/Traversals/Internal.hs:23:13: Not in scope: `<$>'

lib/CabalLenses/Traversals/Internal.hs:24:13: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:24:17: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:25:13: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:25:18:
    Not in scope: `traverse'
    Perhaps you meant `reverse' (imported from Prelude)

lib/CabalLenses/Traversals/Internal.hs:28:21: Not in scope: `<$>'

lib/CabalLenses/Traversals/Internal.hs:28:25: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:28:35: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:28:47: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:31:37: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:33:39: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:34:40:
    Not in scope: `traverse'
    Perhaps you meant `reverse' (imported from Prelude)

lib/CabalLenses/Traversals/Internal.hs:42:13: Not in scope: `<$>'

lib/CabalLenses/Traversals/Internal.hs:43:13: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:43:17: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:44:13: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:44:18:
    Not in scope: `traverse'
    Perhaps you meant `reverse' (imported from Prelude)

lib/CabalLenses/Traversals/Internal.hs:47:21: Not in scope: `<$>'

lib/CabalLenses/Traversals/Internal.hs:47:25: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:48:21: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:49:21: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:49:26:
    Not in scope: `traverse'
    Perhaps you meant `reverse' (imported from Prelude)

lib/CabalLenses/Traversals/Internal.hs:55:13: Not in scope: `<$>'

lib/CabalLenses/Traversals/Internal.hs:55:17: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:56:13: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:56:17:
    Not in scope: `traverse'
    Perhaps you meant `reverse' (imported from Prelude)

lib/CabalLenses/Traversals/Internal.hs:57:13: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:57:18:
    Not in scope: `traverse'
    Perhaps you meant `reverse' (imported from Prelude)

lib/CabalLenses/Traversals/Internal.hs:60:21: Not in scope: `<$>'

lib/CabalLenses/Traversals/Internal.hs:60:25: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:60:35: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:60:47: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:63:37: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:65:39: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:66:40:
    Not in scope: `traverse'
    Perhaps you meant `reverse' (imported from Prelude)

lib/CabalLenses/Traversals/Internal.hs:74:13: Not in scope: `<$>'

lib/CabalLenses/Traversals/Internal.hs:74:17: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:75:13: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:75:17:
    Not in scope: `traverse'
    Perhaps you meant `reverse' (imported from Prelude)

lib/CabalLenses/Traversals/Internal.hs:76:13: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:76:18:
    Not in scope: `traverse'
    Perhaps you meant `reverse' (imported from Prelude)

lib/CabalLenses/Traversals/Internal.hs:79:21: Not in scope: `<$>'

lib/CabalLenses/Traversals/Internal.hs:79:25: Not in scope: `pure'

lib/CabalLenses/Traversals/Internal.hs:80:21: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:81:21: Not in scope: `<*>'

lib/CabalLenses/Traversals/Internal.hs:81:26:
    Not in scope: `traverse'
    Perhaps you meant `reverse' (imported from Prelude)
<<ghc: 1798209856 bytes, 3286 GCs, 37971745/141919368 avg/max bytes residency (9 samples), 281M in use, 0.00 INIT (0.00 elapsed), 1.90 MUT (2.14 elapsed), 1.14 GC (1.14 elapsed) :ghc>>
```

**Comment by dan-t** [comment]
Thanks!

The link to the build matrix is invalid, so I can't see for which ghc version the build failed and why.

Because the `transformer` package is setting the range of the supported `base` packages and therefore the `ghc` version, I would've expected that `cabal` would just select the right `transformer` package based on the used `ghc` version.

**Comment by hvr** [comment]
> The link to the build matrix is invalid, so I can't see for which ghc version the build failed and why.

The link https://matrix.hackage.haskell.org/#/package/cabal-lenses should work; it will however show the most the build-report for the most recent index-state of the package index; but you can use the prev/next buttons to navigate to prior reports

> Because the `transformer` package is setting the range of the supported `base` packages and therefore the `ghc` version, I would've expected that `cabal` would just select the right `transformer` package based on the used `ghc` version.

That's exactly what cabal does! :-)

i.e. you can see at https://matrix.hackage.haskell.org/#/package/transformers which versions of `transformers` are accessible to the respective GHC versions.

However, your code as it stands needs specific versions of the `transformers` API as well as `base` API but the `.cabal` file didn't accurately declare the lower bounds of the respective version ranges.

**Comment by dan-t** [comment]
Thanks again! :)

I don't quite understand the build failure of layers-game-0.6 (https://matrix.hackage.haskell.org/#/package/layers-game)
with ghc 8.6.3. Also the log doesn't tell anything.

I can build layers-game-0.6 with ghc 8.6.3, cabal 2.4.1.0 and 'cabal new-build'
without any issues.

Thanks for any hints!

**Comment by hvr** [comment]
@dan-t the `layers-game` failure is an "indirect failure", this means that one of its dependencies failed to build; unfortunately the UI doesn't yet expose more information about (but it will at some point in the future); but it's most likely a failure due to FFI dependencies not installed in the build job environment -- I will investigate and try to install those to fix the builds

**Comment by hvr** [comment]
@dan-t I found the culprit, see https://github.com/dan-t/Gamgine/pull/1 for details
